# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='minhas_inscricoes', to='evento.Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iteminscricao',
            name='atividade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evento.Atividade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iteminscricao',
            name='inscricao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meus_itens', to='inscricao.Inscricao'),
            preserve_default=False,
        ),
    ]
