# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170831_0953'),
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupomautomatico',
            name='evento',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='meus_cupons', to='core.Evento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='cupom',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minha_inscricao', to='inscricao.Cupom'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='minhas_inscricoes', to='core.Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iteminscricao',
            name='atividade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Atividade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iteminscricao',
            name='inscricao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meus_itens', to='inscricao.Inscricao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamento',
            name='inscricao',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='meu_pagamento', to='inscricao.Inscricao'),
        ),
    ]
