# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170904_1206'),
        ('inscricao', '0002_auto_20170831_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminscricao',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='iteminscricao',
            name='inscricao',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='atividades',
            field=models.ManyToManyField(to='core.Atividade'),
        ),
        migrations.DeleteModel(
            name='ItemInscricao',
        ),
    ]
