# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0002_auto_20170830_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='cupom',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minha_inscricao', to='cupom.Cupom'),
        ),
    ]
