# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacoFisico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacofisico',
            name='espaco_fisico',
            field=models.ManyToManyField(related_name='meus_espacos_fisicos', to='espacoFisico.EspacoFisico'),
        ),
    ]
