# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_auto_20170724_1043'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionamentoAtividadeInscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='evento.Atividade')),
            ],
        ),
        migrations.AddField(
            model_name='inscricao',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='evento.Evento'),
        ),
        migrations.AddField(
            model_name='relacionamentoatividadeinscricao',
            name='inscricao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='usuario.Inscricao'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='atividade',
            field=models.ManyToManyField(through='usuario.RelacionamentoAtividadeInscricao', to='evento.Atividade'),
        ),
    ]
