# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 11:35
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import evento.models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='status',
            field=enumfields.fields.EnumField(default='novo', enum=evento.models.TipoEvento, max_length=25),
        ),
    ]
