# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0001_initial'),
        ('usuario', '0001_initial'),
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='meus_cupons', to='evento.Evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='instituicao',
            field=models.ManyToManyField(to='instituicao.Instituicao'),
        ),
        migrations.AddField(
            model_name='evento',
            name='usuario_criador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='meus_eventos', to='usuario.Usuario'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_atividades', to='evento.Evento'),
        ),
    ]
