# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscricao', '0001_initial'),
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='minhas_atividades', to='evento.Evento'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='responsavel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='minhas_atividades', to='evento.Responsavel'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='inscricao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inscricao.RelacionamentoAtividadeInscricao'),
        ),
        migrations.AddField(
            model_name='cupom',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='meus_cupons', to='evento.Evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='evento_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meus_eventos_satelites', to='evento.Evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='membros',
            field=models.ManyToManyField(related_name='meus_eventos', to=settings.AUTH_USER_MODEL),
        ),
    ]
