# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 11:41
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import evento.models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_evento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='tipoAtividade',
            field=enumfields.fields.EnumField(default='', enum=evento.models.TipoAtividade, max_length=25),
        ),
    ]
