# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_checkin_inscricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minha_agenda', to='evento.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pacote', models.CharField(max_length=25)),
                ('valor_total', models.FloatField(null=True)),
                ('atividades', models.ManyToManyField(to='evento.Atividade')),
            ],
        ),
    ]
