# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 12:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evento', '0002_auto_20170825_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividades', models.ManyToManyField(to='evento.Atividade')),
                ('coordenadores', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
