# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_auto_20170824_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_de_fim',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora_fim',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora_inicio',
            field=models.TimeField(null=True),
        ),
    ]
