# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 04:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_atividade_tipoatividade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividade',
            old_name='tipoAtividade',
            new_name='tipo_atividade',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='instituicao',
        ),
    ]
