# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_trilha'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='nome',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cupom',
            name='nome_cupom',
            field=models.CharField(max_length=25),
        ),
    ]
