# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_auto_20170729_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.CharField(max_length=250),
        ),
    ]
