# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_auto_20170825_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='tema',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
