# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_auto_20170824_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='data_de_fim',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='data_de_inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
