# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 00:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import enumfields.fields
import evento.models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0006_auto_20170801_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='desconto',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='evento',
            name='status',
            field=enumfields.fields.EnumField(default='novo', enum=evento.models.StatusEvento, max_length=25),
        ),
    ]
