# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espacoFisico', '0004_auto_20170828_1142'),
        ('evento', '0006_remove_atividade_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='espacoFisico.EspacoFisico'),
            preserve_default=False,
        ),
    ]
