# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0007_atividade_local'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividade',
            old_name='data_de_fim',
            new_name='horario_final',
        ),
        migrations.RenameField(
            model_name='atividade',
            old_name='data_inicio',
            new_name='horario_inicio',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='hora_inicio',
        ),
    ]
