# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0008_auto_20170828_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='espacoFisico.EspacoFisico'),
        ),
    ]
