# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 21:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evento', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tag', models.CharField(max_length=25)),
                ('evento', models.ManyToManyField(to='evento.Evento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tag', models.CharField(max_length=25)),
                ('usuario', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
