# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instituicao',
            old_name='nomeInstituicao',
            new_name='nome_instituicao',
        ),
    ]
