# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 13:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cupom', models.CharField(max_length=25)),
                ('desconto', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('isautomatico', models.BooleanField()),
                ('data_de_inicio', models.DateTimeField(null=True)),
                ('data_de_fim', models.DateTimeField(null=True)),
                ('evento', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='meus_cupons', to='evento.Evento')),
            ],
        ),
    ]
