# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 15:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cupom', models.CharField(max_length=25)),
                ('desconto', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('data_de_inicio', models.DateTimeField(null=True)),
                ('data_de_fim', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CupomAutomatico',
            fields=[
                ('cupom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cupom.Cupom')),
            ],
            bases=('cupom.cupom',),
        ),
    ]
