# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
        ('cupom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupomautomatico',
            name='evento',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='meus_cupons', to='evento.Evento'),
        ),
    ]
