# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0002_usuario_eventoscriados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='eventosCriados',
        ),
        migrations.AddField(
            model_name='evento',
            name='usuarioCriador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='eventos_app.Usuario'),
        ),
    ]
