# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0003_auto_20170722_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionamentoAtividadeInscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='inscricao',
        ),
        migrations.AddField(
            model_name='relacionamentoatividadeinscricao',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos_app.Atividade'),
        ),
        migrations.AddField(
            model_name='relacionamentoatividadeinscricao',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos_app.Inscricao'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='atividade',
            field=models.ManyToManyField(through='eventos_app.RelacionamentoAtividadeInscricao', to='eventos_app.Atividade'),
        ),
    ]
