# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0005_auto_20170723_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='estadoPagamento',
            new_name='pago',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='pagamento',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='inscricao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='eventos_app.Inscricao'),
        ),
    ]
