# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0006_auto_20170723_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='usuarioCriador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos_app.Usuario'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos_app.Inscricao'),
        ),
    ]
