# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0007_auto_20170723_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='valorTotal',
            field=models.FloatField(null=True),
        ),
    ]
