# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0008_auto_20170723_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='valorAtividade',
            field=models.FloatField(null=True),
        ),
    ]
