# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 16:34
from __future__ import unicode_literals

import comum.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_associacao', enumfields.fields.EnumField(default='default', enum=comum.models.TipoAssociacao, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='EspacoFisico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_espaco_fisico', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(max_length=25)),
                ('unidade_federativa', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TagEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tag', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tag', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
