# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_auto_20170831_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instituicao',
            old_name='uf',
            new_name='unidade_federativa',
        ),
    ]
