# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 12:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='evento',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='minha_agenda', to='core.Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='atividades_proibidas',
            field=models.ManyToManyField(to='core.Atividade'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='minhas_atividades', to='core.Evento'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='responsavel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='minhas_atividades', to='core.Responsavel'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='inscricao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inscricao.ItemInscricao'),
        ),
        migrations.AddField(
            model_name='evento',
            name='evento_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meus_eventos_satelites', to='core.Evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='membros',
            field=models.ManyToManyField(related_name='meus_eventos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trilha',
            name='atividades',
            field=models.ManyToManyField(to='core.Atividade'),
        ),
    ]
