# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='evento',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='minha_agenda', to='core.Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='atividades_proibidas',
            field=models.ManyToManyField(to='core.Atividade'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='minhas_atividades', to='core.Evento'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='responsavel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='minhas_atividades', to='core.Responsavel'),
        ),
        migrations.AddField(
            model_name='evento',
            name='evento_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meus_eventos_satelites', to='core.Evento'),
        ),
    ]
