# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 14:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20170831_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividade',
            old_name='nome_atividade',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='pacote',
            old_name='atividades',
            new_name='atividades_proibidas',
        ),
        migrations.RenameField(
            model_name='pacote',
            old_name='nome_pacote',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='pacote',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='pacote',
            name='pacote',
            field=models.ManyToManyField(related_name='meus_pacotes', to='core.Pacote'),
        ),
        migrations.AddField(
            model_name='pacote',
            name='usuario_criador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pacote',
            name='valor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trilha',
            name='atividades_proibidas',
            field=models.ManyToManyField(to='core.Atividade'),
        ),
        migrations.AddField(
            model_name='trilha',
            name='usuario_criador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trilha',
            name='valor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='usuario_criador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='atividades',
            field=models.ManyToManyField(related_name='minhas_trilhas', to='core.Atividade'),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='coordenadores',
            field=models.ManyToManyField(related_name='minhas_trilhas', to=settings.AUTH_USER_MODEL),
        ),
    ]
