# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170901_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacote',
            name='atividades_proibidas',
        ),
        migrations.RemoveField(
            model_name='trilha',
            name='atividades_proibidas',
        ),
    ]
