# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170901_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='horario_final',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='horario_inicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_de_fim',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
