# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170902_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_de_fim',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(null=True),
        ),
    ]
