# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 15:06
from __future__ import unicode_literals

import core.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170904_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='inscricao',
        ),
        migrations.AlterField(
            model_name='atividade',
            name='tipo_atividade',
            field=enumfields.fields.EnumField(default='outros', enum=core.models.TipoAtividade, max_length=25),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=enumfields.fields.EnumField(default='outros', enum=core.models.TipoEvento, max_length=25),
        ),
    ]
