# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170904_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='horario_final',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='horario_inicio',
            field=models.DateField(null=True),
        ),
    ]
