# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorTotal', models.FloatField(null=True)),
                ('pago', models.BooleanField(default=False)),
            ],
        ),
    ]
