# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0001_initial'),
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='inscricao',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='meu_pagamento', to='inscricao.Inscricao'),
        ),
    ]
