# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='valorTotal',
            new_name='valor_total',
        ),
    ]
