# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0002_auto_20170727_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='valor_total',
            field=models.FloatField(default=0),
        ),
    ]
